### ISSUE TITLE
Manifold -> eScholarship

### ISSUE THREAD

**Issue by everreau** [eScholarship/jschol#735]
We currently have 1 project (in multiple languages) on Manifold, Ultrasound in Resource-Limited Settings https://manifold.escholarship.org/projects/ultrasound-in-resource-limited-settings

After several years, it seems that we're not likely to launch additional projects on Manifold. To reduce the amount of things we need to maintain / upgrade, we'd like to try getting this publication into eScholarship.

As of now, the only way (aside from the command line) we have for getting HTML items into eScholarship is via Janeway. Justin has tried publishing 1 item, but the HTML is not displaying: https://pub-jschol2-stg.escholarship.org/uc/item/tt7mzx2n
here is the item in Janeway: https://journalpub-dev.escholarship.org/ultrasound_en/manage/archive/article/136921/

**Comment by everreau** [comment]
@justingonder do you have a link to your test case in jschol or janeway?

**Comment by justingonder** [comment]
d'oh - my clipboard pasted the manifold link twice 🙈 updated above. sorry about that @everreau

**Comment by everreau** [comment]
@justingonder the html file didn't have headers/declarations.  I added them to the html directly on submit and it's looking OK now.  Here's the snippet I added:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
    <meta charset="utf-8"/>
</head>
<body>
    [HTMLDOC]
</body>
</html>
```

**Comment by everreau** [comment]
ok, I updated the html file in janeway and republished so it's working now.  I looked into the image thing and realized that the connector is making an assumption about what kinds of galleys have images so there will have to be a minor connector change before that will work.

**Comment by everreau** [comment]
https://github.com/eScholarship/janeway_to_escholarship/pull/39

**Comment by everreau** [comment]
@justingonder this fix is released to dev.  It should send images attached to the html galleys now.

**Comment by everreau** [comment]
Chad set up an sftp server on the manifold server itself.  I am able to login from the server but attempted export fails.  I cannot find any information about what is failing about it.

<img width="650" height="455" alt="Image" src="https://github.com/user-attachments/assets/afb54047-6eb4-4bf2-a4be-b072765a8631" />

I've looked through the logs I've found on the server and I don't see anything about it.  The docs are deeply unhelpful.  All it says is to check with the sysadmin to test if the server can connect (it can).

**Comment by nicktahani** [comment]
@everreau sure, let me know if there's anything I can help with.

**Comment by everreau** [comment]
@justingonder 2 more import questions:

1. Do you want the items added to an issue upon import?
2. What do you want the publication date set to?

**Comment by everreau** [comment]
New example: https://pub-jschol2-stg.escholarship.org/uc/item/ttbz8vsk

**Comment by everreau** [comment]
publication_date isn't entered in manifold so I used created_at for the date_published for now.

**Comment by everreau** [comment]
@justingonder unless you have comments on any of the above I can go ahead and import everything to dev for review.  Do you want me to just import it to demo or should we create a new journal that is similar to what we'll use in prd?  And let me know if you want me to add them to an issue by default.

**Comment by justingonder** [comment]
Janeway DEV: https://journalpub-dev.escholarship.org/usinrls
jSchol STG: https://pub-jschol2-stg.escholarship.org/uc/usinrls

I created Volume 0, Issue 0 to put the content in, which we will need to do in order for section headings to work. Using 0, 0 also enables us to overwrite the volume and issue information utilizing our "Articles in Press" customization.

**Comment by everreau** [comment]
Full import complete on dev: https://journalpub-dev.escholarship.org/usinrls/manage/issues/4349/

**Comment by everreau** [comment]
need to investigate API failures:

```
ERROR 2026-04-14 09:21:20,744 logic P:2440 T:140370273545728 b'STORED'
Traceback (most recent call last):
  File "/apps/eschol/janeway/src/plugins/eschol/logic.py", line 573, in issue_to_eschol
    apub = send_article(a, configured, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/janeway/src/plugins/eschol/logic.py", line 445, in send_article
    if not article.issue:
           ^^^^^^^^^^^^^
  File "/apps/eschol/janeway/src/submission/models.py", line 1311, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/janeway/src/utils/function_cache.py", line 24, in y
    result = django_cache.get(key)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/.janewayenv/lib64/python3.11/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    return self._cache.get(key, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/.janewayenv/lib64/python3.11/site-packages/pymemcache/client/hash.py", line 347, in get
    return self._run_cmd("get", key, default, default=default, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/.janewayenv/lib64/python3.11/site-packages/pymemcache/client/hash.py", line 322, in _run_cmd
    return self._safely_run_func(client, func, default_val, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/.janewayenv/lib64/python3.11/site-packages/pymemcache/client/hash.py", line 211, in _safely_run_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/.janewayenv/lib64/python3.11/site-packages/pymemcache/client/base.py", line 687, in get
    return self._fetch_cmd(b"get", [key], False, key_prefix=self.key_prefix).get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/eschol/.janewayenv/lib64/python3.11/site-packages/pymemcache/client/base.py", line 1165, in _fetch_cmd
    raise MemcacheUnknownError(line[:32])
```
```
An unexpected error occured when sending 140772 - Miliary Tuberculosis to eScholarship: HTTPSConnectionPool(host='pub-jschol2-stg.escholarship.org', port=443): Read timed out. (read timeout=30)
```

**Comment by everreau** [comment]
I'm thinking both of these errors may have to do with the current janeway-dev server being undersized.

**Comment by everreau** [comment]
I had the janeway-dev server sized up which got through more of the the issue but there was still an error that appeared to have to do with concurrency and memcached.  I tweaked some cache settings and we go through the full publication.  Not totally sure if this made a difference or if it's just didn't happen to occur this time around.  Anyway, full issue is published.

**Comment by everreau** [comment]
@justingonder this is ready for review.  This is ready to run on prod as soon as the journal is set up there unless you have additional feedback.

**Comment by justingonder** [comment]
Dev looking good.
Moving on to STG, where we'll separate the contents into issues by language:
| Issue | Language | Manifold URL |
| :---- | :----------- | :------------ |
| 1.1 | ENGLISH | https://manifold.escholarship.org/projects/ultrasound-in-resource-limited-settings |
| 1.2 | FRANÇAIS | https://manifold.escholarship.org/projects/ultrasound-in-resource-limited-settings-french |
| 1.3 | PORTUGUES | https://manifold.escholarship.org/projects/ultrasound-in-resource-limited-settings-portuguese |
| 1.4 | ESPAÑOL | https://manifold.escholarship.org/projects/ultrasound-in-resource-limited-settings-a-case-based-open-access-text-spanish | 

https://journalpub-stg.escholarship.org/usinrls/manage/issues/

**Comment by everreau** [comment]
@justingonder imported to stg.  I added some logging to the connector and pushed one of the issues (did not observe the same problem we've seen a few times on dev)

**Comment by justingonder** [comment]
@everreau this looks good on stg! https://pub-jschol2-stg.escholarship.org/uc/usinrls
I think we're ready for PRD - I've got the Janeway setup done here: https://journalpub.escholarship.org/usinrls/

**Comment by everreau** [comment]
@justingonder imported to prd.  I created the issues so you may want to review the setup of those to make sure I got it all right.
